name: mobile_smile_multifab
description: "Mobile Smile Multifab Application"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9

  # Networking
  dio: ^5.4.0
  connectivity_plus: ^6.0.3
  url_launcher: ^6.3.0

  # Permissions & Scan
  permission_handler: ^11.3.1
  mobile_scanner: ^5.1.1

  # Location & Maps
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Camera & Media
  camera: ^0.10.5+9
  image_picker: ^1.0.7

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.3.3
  intl: ^0.19.0

  # Background & Notifications
  workmanager: ^0.5.2
  flutter_local_notifications: ^17.0.0

  # Firebase
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0

  # WebView
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700